const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.bound,
		C3.Behaviors.scrollto,
		C3.Behaviors.Pin,
		C3.Plugins.Keyboard,
		C3.Behaviors.LOS,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Plugins.Audio,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Anchor,
		C3.Behaviors.Flash,
		C3.Plugins.Mouse,
		C3.Behaviors.Fade,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Exps.ImageOffsetX,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetFlipped,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Platform.Cnds.OnMove,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Behaviors.Platform.Acts.SetIgnoreInput,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Exps.X,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.SetVar
	];
};
self.C3_JsPropNameTable = [
	{Background1: 0},
	{Sólido: 0},
	{Ground: 0},
	{PlayerHealth: 0},
	{Plataforma: 0},
	{RestritoAoLayout: 0},
	{CentrarEm: 0},
	{Player: 0},
	{Fixar: 0},
	{Samurai: 0},
	{Teclado: 0},
	{Health: 0},
	{Action: 0},
	{Type: 0},
	{CampoDeVisão: 0},
	{Wolf: 0},
	{Projétil: 0},
	{DestruirForaDoLayout: 0},
	{Arrow: 0},
	{Dead: 0},
	{Áudio: 0},
	{StartBackground: 0},
	{Âncora: 0},
	{Continue: 0},
	{Sky: 0},
	{Clouds1: 0},
	{GameOverBackground: 0},
	{Piscar: 0},
	{Start: 0},
	{Mouse: 0},
	{House: 0},
	{Crate: 0},
	{Gate: 0},
	{Endpoint1: 0},
	{EndGameBackground: 0},
	{PressAnyButton: 0},
	{Esmaecer: 0},
	{BloodSplash: 0},
	{Tiles: 0},
	{Kills: 0},
	{BlackPanel: 0},
	{Title: 0},
	{Moon: 0},
	{MoonRed: 0},
	{Endpoint2: 0},
	{Clouds2: 0},
	{Background2: 0}
];

self.InstanceType = {
	Background1: class extends self.ITiledBackgroundInstance {},
	Ground: class extends self.ITiledBackgroundInstance {},
	Player: class extends self.ISpriteInstance {},
	Samurai: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Wolf: class extends self.ISpriteInstance {},
	Arrow: class extends self.ISpriteInstance {},
	Dead: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	StartBackground: class extends self.ITiledBackgroundInstance {},
	Continue: class extends self.ISpriteFontInstance {},
	Sky: class extends self.ITiledBackgroundInstance {},
	Clouds1: class extends self.ITiledBackgroundInstance {},
	GameOverBackground: class extends self.ITiledBackgroundInstance {},
	Start: class extends self.ISpriteFontInstance {},
	Mouse: class extends self.IInstance {},
	House: class extends self.ISpriteInstance {},
	Crate: class extends self.ISpriteInstance {},
	Gate: class extends self.ISpriteInstance {},
	Endpoint1: class extends self.ISpriteInstance {},
	EndGameBackground: class extends self.ISpriteInstance {},
	PressAnyButton: class extends self.ISpriteFontInstance {},
	BloodSplash: class extends self.ISpriteInstance {},
	Tiles: class extends self.ITiledBackgroundInstance {},
	Kills: class extends self.ISpriteFontInstance {},
	BlackPanel: class extends self.ITiledBackgroundInstance {},
	Title: class extends self.ISpriteFontInstance {},
	Moon: class extends self.ISpriteInstance {},
	MoonRed: class extends self.ISpriteInstance {},
	Endpoint2: class extends self.ISpriteInstance {},
	Clouds2: class extends self.ITiledBackgroundInstance {},
	Background2: class extends self.ITiledBackgroundInstance {}
}